change the project core name to nodetalk

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,7 +23,7 @@ jobs:
         run:  make -C src all
 
       - name: Binary exists check
-        run: test -f ./src/bomachat && echo "✅ Binary found" || (echo "❌ Binary missing" && exit 1)
+        run: test -f ./src/nodetalk && echo "✅ Binary found" || (echo "❌ Binary missing" && exit 1)
 
   
   test:
@@ -42,7 +42,7 @@ jobs:
         run: make -C src all
 
       - name: Start server in background
-        run: ./src/bomachat 6667 testpass &
+        run: ./src/nodetalk 6667 testpass &
 
       - name: Wait for server to be ready
         run: sleep 2
@@ -54,7 +54,7 @@ jobs:
           (echo "❌ Server not responding" && exit 1)
 
       - name: Kill server
-        run: pkill ./src/bomachat || true
+        run: pkill ./src/nodetalk || true
       
 
   docker-build:
